apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ttc-injection-gpu-
spec:
  serviceAccountName: workflow
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 64Gi
  entrypoint: main
  arguments:
    parameters:
      - name: method
        value: fixed_final_size
      - name: synth_split
        value: 0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1
      - name: val_test_sample
        value: 30000
      - name: final_size
        value: 50000
      - name: train_original_sample
        value: 50000
      - name: preprocessed
        value: true,false
      - name: embedding_dim
        value: 64,128,256
      - name: num_epochs
        value: 15
      - name: lr
        value: 1e-3,5e-4,1e-4
      - name: patience_early_stopping
        value : 2
      - name: synth_path
        value: s3://projet-ape/synthetic_data_test/naive/NAF2025_FR/2026-03-16_google-gemma-3-27b-it_temp14_fewshot6_exhaustive.parquet,s3://projet-ape/synthetic_data_test/naive/NAF2025_FR/retext-2026-05-29_gemma4-26b-moe_temp10_fewshot6_exhaustive.parquets3://projet-ape/synthetic_data_test/naive/NAF2025_FR/retext-2026-06-05_gemma4-26b-moe_temp10_fewshot6_exhaustive.parquet
      - name: original_train_path
        value: s3://projet-ape/data/08112022_27102024/naf2025/split/df_train.parquet
      - name: original_val_path
        value: s3://projet-ape/data/08112022_27102024/naf2025/split/df_val.parquet
      - name: original_test_path
        value: s3://projet-ape/data/08112022_27102024/naf2025/split/df_test.parquet
  templates:
    - name: main
      inputs:
        parameters:
        - name: method
        - name: synth_split
        - name: val_test_sample
        - name: final_size
        - name: train_original_sample
        - name: preprocessed
        - name: embedding_dim
        - name: num_epochs
        - name: lr
        - name: patience_early_stopping
        - name: synth_path
        - name: original_train_path
        - name: original_val_path
        - name: original_test_path
      container:
        image: inseefrlab/onyxia-vscode-pytorch:py3.13.5-gpu
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: 4000m
            memory: 100Gi
          requests:
              nvidia.com/gpu: 1  # Add GPU to requests too
              cpu: 300m
              memory: 30Gi
        command: ["/bin/bash", -c]
        args:
          - |
            set -e  # Exit on error
            set -x  # Print commands for debugging

            # Clone repository and submodules
            git clone -b main https://github.com/mateomorin/funathon-project2.git
            cd funathon-project2/

            # Setup
            uv sync --extra gpu

            # Run MLflow experiment
            uv run train.py -m \
                training_config.accelerator=cuda \
                injection.method={{inputs.parameters.method}} \
                injection.synth_split={{inputs.parameters.synth_split}} \
                injection.val_test_sample={{inputs.parameters.val_test_sample}} \
                injection.final_size={{inputs.parameters.final_size}} \
                injection.train_original_sample={{inputs.parameters.train_original_sample}} \
                tokenizer.preprocessed={{inputs.parameters.preprocessed}} \
                model.embedding_dim={{inputs.parameters.embedding_dim}} \
                training_config.num_epochs={{inputs.parameters.num_epochs}} \
                training_config.lr={{inputs.parameters.lr}} \
                training_config.patience_early_stopping={{inputs.parameters.patience_early_stopping}} \
                data.synth_path={{inputs.parameters.synth_path}} \
                data.original_train_path={{inputs.parameters.original_train_path}} \
                data.original_val_path={{inputs.parameters.original_val_path}} \
                data.original_test_path={{inputs.parameters.original_test_path}}

        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          # env var for s3 connexion
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-read-only
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-read-only
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_DEFAULT_REGION
            value: us-east-1
          - name: AWS_S3_ENDPOINT
            value: minio.lab.sspcloud.fr
          - name: MLFLOW_S3_ENDPOINT_URL
            value: https://minio.lab.sspcloud.fr
          - name: MLFLOW_TRACKING_URI
            valueFrom:
              secretKeyRef:
                name: my-mlflow-creds
                key: MLFLOW_TRACKING_URI 
          - name: MLFLOW_TRACKING_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-mlflow-creds
                key: MLFLOW_TRACKING_PASSWORD 
          - name: MLFLOW_TRACKING_USERNAME
            valueFrom:
              secretKeyRef:
                name: my-mlflow-creds
                key: MLFLOW_TRACKING_USERNAME 
          