apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: augmented-codif-ape-
spec:
  serviceAccountName: workflow
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 64Gi
  entrypoint: main
  arguments:
    parameters:
      - name: different_val_test_sample
        value: 30000
      - name: different_method
        value: fixed_final_size
      - name: different_lr
        value: 1e-3,5e-4,1e-4
      - name: different_split
        value: 0,0.2,0.4,0.6,0.8,1
      - name: different_embedding_dim
        value: 64,128,256
      - name: different_preprocessing
        value: true,false
      - name: data_naive
        value: s3://projet-ape/synthetic_data_test/naive/NAF2025_FR/2026-03-16_google-gemma-3-27b-it_temp14_fewshot6_exhaustive.parquet
      - name: data_retext
        value: s3://projet-ape/synthetic_data_test/naive/NAF2025_FR/retext-2026-05-29_gemma4-26b-moe_temp10_fewshot6_exhaustive.parquet,s3://projet-ape/synthetic_data_test/naive/NAF2025_FR/retext-2026-05-29_gemma4-26b-moe_temp10_fewshot6_exhaustive.parquet
  templates:
    - name: main
      inputs:
        parameters:
        - name: different_val_test_sample
        - name: different_method
        - name: different_lr
        - name: different_split
        - name: different_preprocessing
        - name: data_naive
        - name: data_retext
      container:
        image: inseefrlab/onyxia-vscode-pytorch:py3.13.5-gpu
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: 4000m
            memory: 100Gi
          requests:
              nvidia.com/gpu: 1  # Add GPU to requests too
              cpu: 300m
              memory: 30Gi
        command: ["/bin/bash", -c]
        args:
          - |
            set -e  # Exit on error
            set -x  # Print commands for debugging

            # Clone repository and submodules
            git clone -b main https://github.com/mateomorin/funathon-project2.git
            cd funathon-project2/

            # Setup
            uv sync --extra gpu

            # Run MLflow experiment
            uv run train.py -m \
                training_config.accelerator=cuda \
                injection.val_test_sample={{inputs.parameters.different_val_test_sample}} \
                injection.method={{inputs.parameters.different_method}} \
                training_config.lr={{inputs.parameters.different_lr}} \
                tokenizer.preprocessed={{inputs.parameters.different_preprocessing}} \
                injection.synth_split={{inputs.parameters.different_split}} \
                model.embedding_dim={{inputs.parameters.different_embedding_dim}} \
                data.synth_path={{inputs.parameters.data_naive}},{{inputs.parameters.data_retext}}

        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          # env var for s3 connexion
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-read-only
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-read-only
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_DEFAULT_REGION
            value: us-east-1
          - name: AWS_S3_ENDPOINT
            value: minio.lab.sspcloud.fr
          - name: MLFLOW_S3_ENDPOINT_URL
            value: https://minio.lab.sspcloud.fr
          - name: MLFLOW_TRACKING_URI
            valueFrom:
              secretKeyRef:
                name: my-mlflow-creds
                key: MLFLOW_TRACKING_URI 
          - name: MLFLOW_TRACKING_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-mlflow-creds
                key: MLFLOW_TRACKING_PASSWORD 
          - name: MLFLOW_TRACKING_USERNAME
            valueFrom:
              secretKeyRef:
                name: my-mlflow-creds
                key: MLFLOW_TRACKING_USERNAME 
          